type: google.api.Service
config_version: 3

http:
  rules:
    #获取后台软件版本号
    - selector: camel.api.AgvService.GetVersion
      post: /camel/v1/GetVersion
      body: "*"
    #获取当前小车运行状态
    - selector: camel.api.AgvService.GetAgvState
      post: /camel/v1/GetAgvState
      body: "*"
    #UI向Camel请求配置信息
    - selector: camel.api.AgvService.RequestUIConfig
      post: /camel/v1/RequestUIConfig
      body: "*"
    #获取系统信息
    - selector: camel.api.AgvService.GetSystemStatus
      post: /camel/v1/GetSystemStatus
      body: "*"
    #获取小车执行的任务信息   
    - selector: camel.api.AgvService.GetAgvStateInAgvs
      post: /camel/v1/GetAgvStateInAgvs
      body: "*"
    #客户端发送给服务器的请求
    - selector: camel.api.AgvService.SendToAgvs
      post: /camel/v1/SendToAgvs
      body: "*"
    #客户端控制小车的一些操作
    - selector: camel.api.AgvService.ControlAgv
      post: /camel/v1/ControlAgv
      body: "*"
    #获取小车当前正在运行的路径
    - selector: camel.api.AgvService.GetCamelPathCollection
      post: /camel/v1/GetCamelPathCollection
      body: "*"
    #客户端模拟任务发布
    - selector: camel.api.AgvService.RoutePlan
      post: /camel/v1/RoutePlan
      body: "*"
    #设置避障区域
    - selector: camel.api.AgvService.SetAvoidanceArea
      post: /camel/v1/SetAvoidanceArea
      body: "*"
    #模拟手柄控制小车
    - selector: camel.api.AgvService.StickControl
      post: /camel/v1/StickControl
      body: "*"
    #申请手柄控制
    - selector: camel.api.AgvService.ApplyStickControl
      post: /camel/v1/ApplyStickControl
      body: "*"
    #重启小车
    - selector: camel.api.AgvService.CarRestart
      post: /camel/v1/CarRestart
      body: "*"
    #更新小车站点坐标
    - selector: camel.api.AgvService.UpdateStationPose
      post: /camel/v1/UpdateStationPose
      body: "*"
    #任务调度呼叫及配置
    - selector: camel.api.AgvService.TaskAllocationOperation
      post: /camel/v1/TaskAllocationOperation
      body: "*"
    #重置任务列表
    - selector: camel.api.AgvService.AssignAllocationTasks
      post: /camel/v1/AssignAllocationTasks
      body: "*"

