type: google.api.Service
config_version: 3

http:
  rules:
    - selector: responseBody.ResponseBodyService.GetResponseBody
      get: /proto/responseBody/response_body/get/{data}

    - selector: responseBody.ResponseBodyService.ListResponseStrings
      post: /proto/responseBody/response_body/list
      body: "*"
