// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: camel_grpc.proto
#ifndef GRPC_camel_5fgrpc_2eproto__INCLUDED
#define GRPC_camel_5fgrpc_2eproto__INCLUDED

#include "camel_grpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace camel {
namespace api {

// 将agv内部数据提供给外部grpc调用者
class AgvService final {
 public:
  static constexpr char const* service_full_name() {
    return "camel.api.AgvService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 申请手柄控制
    virtual ::grpc::Status ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::camel::api::Token* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::camel::api::Token>> AsyncApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::camel::api::Token>>(AsyncApplyStickControlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::camel::api::Token>> PrepareAsyncApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::camel::api::Token>>(PrepareAsyncApplyStickControlRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 申请手柄控制
      virtual void ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::camel::api::Token>* AsyncApplyStickControlRaw(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::camel::api::Token>* PrepareAsyncApplyStickControlRaw(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::camel::api::Token* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::camel::api::Token>> AsyncApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::camel::api::Token>>(AsyncApplyStickControlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::camel::api::Token>> PrepareAsyncApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::camel::api::Token>>(PrepareAsyncApplyStickControlRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response, std::function<void(::grpc::Status)>) override;
      void ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::camel::api::Token>* AsyncApplyStickControlRaw(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::camel::api::Token>* PrepareAsyncApplyStickControlRaw(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ApplyStickControl_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 申请手柄控制
    virtual ::grpc::Status ApplyStickControl(::grpc::ServerContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ApplyStickControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ApplyStickControl() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ApplyStickControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ApplyStickControl(::grpc::ServerContext* /*context*/, const ::camel::api::GamepadControl* /*request*/, ::camel::api::Token* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestApplyStickControl(::grpc::ServerContext* context, ::camel::api::GamepadControl* request, ::grpc::ServerAsyncResponseWriter< ::camel::api::Token>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ApplyStickControl<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ApplyStickControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ApplyStickControl() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::camel::api::GamepadControl, ::camel::api::Token>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response) { return this->ApplyStickControl(context, request, response); }));}
    void SetMessageAllocatorFor_ApplyStickControl(
        ::grpc::MessageAllocator< ::camel::api::GamepadControl, ::camel::api::Token>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::camel::api::GamepadControl, ::camel::api::Token>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ApplyStickControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ApplyStickControl(::grpc::ServerContext* /*context*/, const ::camel::api::GamepadControl* /*request*/, ::camel::api::Token* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ApplyStickControl(
      ::grpc::CallbackServerContext* /*context*/, const ::camel::api::GamepadControl* /*request*/, ::camel::api::Token* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ApplyStickControl<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ApplyStickControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ApplyStickControl() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ApplyStickControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ApplyStickControl(::grpc::ServerContext* /*context*/, const ::camel::api::GamepadControl* /*request*/, ::camel::api::Token* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ApplyStickControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ApplyStickControl() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ApplyStickControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ApplyStickControl(::grpc::ServerContext* /*context*/, const ::camel::api::GamepadControl* /*request*/, ::camel::api::Token* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestApplyStickControl(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ApplyStickControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ApplyStickControl() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ApplyStickControl(context, request, response); }));
    }
    ~WithRawCallbackMethod_ApplyStickControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ApplyStickControl(::grpc::ServerContext* /*context*/, const ::camel::api::GamepadControl* /*request*/, ::camel::api::Token* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ApplyStickControl(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ApplyStickControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ApplyStickControl() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::camel::api::GamepadControl, ::camel::api::Token>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::camel::api::GamepadControl, ::camel::api::Token>* streamer) {
                       return this->StreamedApplyStickControl(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ApplyStickControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ApplyStickControl(::grpc::ServerContext* /*context*/, const ::camel::api::GamepadControl* /*request*/, ::camel::api::Token* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedApplyStickControl(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::camel::api::GamepadControl,::camel::api::Token>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ApplyStickControl<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ApplyStickControl<Service > StreamedService;
};

}  // namespace api
}  // namespace camel


#endif  // GRPC_camel_5fgrpc_2eproto__INCLUDED
