// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: camel_grpc.proto

#include "camel_grpc.pb.h"
#include "camel_grpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace camel {
namespace api {

static const char* AgvService_method_names[] = {
  "/camel.api.AgvService/ApplyStickControl",
};

std::unique_ptr< AgvService::Stub> AgvService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AgvService::Stub> stub(new AgvService::Stub(channel, options));
  return stub;
}

AgvService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ApplyStickControl_(AgvService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AgvService::Stub::ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::camel::api::Token* response) {
  return ::grpc::internal::BlockingUnaryCall< ::camel::api::GamepadControl, ::camel::api::Token, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ApplyStickControl_, context, request, response);
}

void AgvService::Stub::async::ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::camel::api::GamepadControl, ::camel::api::Token, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ApplyStickControl_, context, request, response, std::move(f));
}

void AgvService::Stub::async::ApplyStickControl(::grpc::ClientContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ApplyStickControl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::camel::api::Token>* AgvService::Stub::PrepareAsyncApplyStickControlRaw(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::camel::api::Token, ::camel::api::GamepadControl, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ApplyStickControl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::camel::api::Token>* AgvService::Stub::AsyncApplyStickControlRaw(::grpc::ClientContext* context, const ::camel::api::GamepadControl& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncApplyStickControlRaw(context, request, cq);
  result->StartCall();
  return result;
}

AgvService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgvService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgvService::Service, ::camel::api::GamepadControl, ::camel::api::Token, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgvService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::camel::api::GamepadControl* req,
             ::camel::api::Token* resp) {
               return service->ApplyStickControl(ctx, req, resp);
             }, this)));
}

AgvService::Service::~Service() {
}

::grpc::Status AgvService::Service::ApplyStickControl(::grpc::ServerContext* context, const ::camel::api::GamepadControl* request, ::camel::api::Token* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace camel
}  // namespace api

