// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef PICTURE_ODB_HXX
#define PICTURE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "picture.hxx"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Picture
  //
  template <>
  struct class_traits< ::Picture >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Picture >
  {
    public:
    typedef ::Picture object_type;
    typedef ::Picture* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef short unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // Picture
  //
  template <typename A>
  struct query_columns< ::Picture, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        short unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // name
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    name_type_;

    static const name_type_ name;

    // bytes
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::size_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    bytes_type_;

    static const bytes_type_ bytes;

    // resolution
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    resolution_type_;

    static const resolution_type_ resolution;

    // type
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    type_type_;

    static const type_type_ type;

    // path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    path_type_;

    static const path_type_ path;

    // timeUpload
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::time_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    timeUpload_type_;

    static const timeUpload_type_ timeUpload;

    // timeModify
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::time_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    timeModify_type_;

    static const timeModify_type_ timeModify;

    // owner
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    owner_type_;

    static const owner_type_ owner;
  };

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::id_type_
  query_columns< ::Picture, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::name_type_
  query_columns< ::Picture, id_sqlite, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::bytes_type_
  query_columns< ::Picture, id_sqlite, A >::
  bytes (A::table_name, "\"bytes\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::resolution_type_
  query_columns< ::Picture, id_sqlite, A >::
  resolution (A::table_name, "\"resolution\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::type_type_
  query_columns< ::Picture, id_sqlite, A >::
  type (A::table_name, "\"type\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::path_type_
  query_columns< ::Picture, id_sqlite, A >::
  path (A::table_name, "\"path\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::timeUpload_type_
  query_columns< ::Picture, id_sqlite, A >::
  timeUpload (A::table_name, "\"timeUpload\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::timeModify_type_
  query_columns< ::Picture, id_sqlite, A >::
  timeModify (A::table_name, "\"timeModify\"", 0);

  template <typename A>
  const typename query_columns< ::Picture, id_sqlite, A >::owner_type_
  query_columns< ::Picture, id_sqlite, A >::
  owner (A::table_name, "\"owner\"", 0);

  template <typename A>
  struct pointer_query_columns< ::Picture, id_sqlite, A >:
    query_columns< ::Picture, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Picture, id_sqlite >:
    public access::object_traits< ::Picture >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // name_
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // bytes_
      //
      long long bytes_value;
      bool bytes_null;

      // resolution_
      //
      details::buffer resolution_value;
      std::size_t resolution_size;
      bool resolution_null;

      // type_
      //
      details::buffer type_value;
      std::size_t type_size;
      bool type_null;

      // path_
      //
      details::buffer path_value;
      std::size_t path_size;
      bool path_null;

      // timeUpload_
      //
      long long timeUpload_value;
      bool timeUpload_null;

      // timeModify_
      //
      long long timeModify_value;
      bool timeModify_null;

      // owner_
      //
      details::buffer owner_value;
      std::size_t owner_size;
      bool owner_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Picture, id_common >:
    public access::object_traits_impl< ::Picture, id_sqlite >
  {
  };

  // Picture
  //
}

#include "picture-odb.ixx"

#include <odb/post.hxx>

#endif // PICTURE_ODB_HXX
