// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "picture-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // Picture
  //

  struct access::object_traits_impl< ::Picture, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::Picture, id_sqlite >::id_type
  access::object_traits_impl< ::Picture, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::Picture, id_sqlite >::id_type
  access::object_traits_impl< ::Picture, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Picture, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = false;

    // name_
    //
    if (t[1UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // bytes_
    //
    t[2UL] = false;

    // resolution_
    //
    if (t[3UL])
    {
      i.resolution_value.capacity (i.resolution_size);
      grew = true;
    }

    // type_
    //
    if (t[4UL])
    {
      i.type_value.capacity (i.type_size);
      grew = true;
    }

    // path_
    //
    if (t[5UL])
    {
      i.path_value.capacity (i.path_size);
      grew = true;
    }

    // timeUpload_
    //
    t[6UL] = false;

    // timeModify_
    //
    t[7UL] = false;

    // owner_
    //
    if (t[8UL])
    {
      i.owner_value.capacity (i.owner_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::Picture, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // name_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.name_value.data ();
    b[n].size = &i.name_size;
    b[n].capacity = i.name_value.capacity ();
    b[n].is_null = &i.name_null;
    n++;

    // bytes_
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.bytes_value;
    b[n].is_null = &i.bytes_null;
    n++;

    // resolution_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.resolution_value.data ();
    b[n].size = &i.resolution_size;
    b[n].capacity = i.resolution_value.capacity ();
    b[n].is_null = &i.resolution_null;
    n++;

    // type_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.type_value.data ();
    b[n].size = &i.type_size;
    b[n].capacity = i.type_value.capacity ();
    b[n].is_null = &i.type_null;
    n++;

    // path_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.path_value.data ();
    b[n].size = &i.path_size;
    b[n].capacity = i.path_value.capacity ();
    b[n].is_null = &i.path_null;
    n++;

    // timeUpload_
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.timeUpload_value;
    b[n].is_null = &i.timeUpload_null;
    n++;

    // timeModify_
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.timeModify_value;
    b[n].is_null = &i.timeModify_null;
    n++;

    // owner_
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.owner_value.data ();
    b[n].size = &i.owner_size;
    b[n].capacity = i.owner_value.capacity ();
    b[n].is_null = &i.owner_null;
    n++;
  }

  void access::object_traits_impl< ::Picture, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Picture, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // id_
    //
    if (sk == statement_insert)
    {
      short unsigned int const& v =
        o.id_;

      bool is_null (false);
      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        v);
      i.id_null = is_null;
    }

    // name_
    //
    {
      ::std::string const& v =
        o.name_;

      bool is_null (false);
      std::size_t cap (i.name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.name_value,
        i.name_size,
        is_null,
        v);
      i.name_null = is_null;
      grew = grew || (cap != i.name_value.capacity ());
    }

    // bytes_
    //
    {
      ::std::size_t const& v =
        o.bytes_;

      bool is_null (false);
      sqlite::value_traits<
          ::std::size_t,
          sqlite::id_integer >::set_image (
        i.bytes_value,
        is_null,
        v);
      i.bytes_null = is_null;
    }

    // resolution_
    //
    {
      ::std::string const& v =
        o.resolution_;

      bool is_null (false);
      std::size_t cap (i.resolution_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.resolution_value,
        i.resolution_size,
        is_null,
        v);
      i.resolution_null = is_null;
      grew = grew || (cap != i.resolution_value.capacity ());
    }

    // type_
    //
    {
      ::std::string const& v =
        o.type_;

      bool is_null (false);
      std::size_t cap (i.type_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.type_value,
        i.type_size,
        is_null,
        v);
      i.type_null = is_null;
      grew = grew || (cap != i.type_value.capacity ());
    }

    // path_
    //
    {
      ::std::string const& v =
        o.path_;

      bool is_null (false);
      std::size_t cap (i.path_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.path_value,
        i.path_size,
        is_null,
        v);
      i.path_null = is_null;
      grew = grew || (cap != i.path_value.capacity ());
    }

    // timeUpload_
    //
    {
      ::time_t const& v =
        o.timeUpload_;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i.timeUpload_value,
        is_null,
        v);
      i.timeUpload_null = is_null;
    }

    // timeModify_
    //
    {
      ::time_t const& v =
        o.timeModify_;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i.timeModify_value,
        is_null,
        v);
      i.timeModify_null = is_null;
    }

    // owner_
    //
    {
      ::std::string const& v =
        o.owner_;

      bool is_null (false);
      std::size_t cap (i.owner_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.owner_value,
        i.owner_size,
        is_null,
        v);
      i.owner_null = is_null;
      grew = grew || (cap != i.owner_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::Picture, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      short unsigned int& v =
        o.id_;

      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // name_
    //
    {
      ::std::string& v =
        o.name_;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.name_value,
        i.name_size,
        i.name_null);
    }

    // bytes_
    //
    {
      ::std::size_t& v =
        o.bytes_;

      sqlite::value_traits<
          ::std::size_t,
          sqlite::id_integer >::set_value (
        v,
        i.bytes_value,
        i.bytes_null);
    }

    // resolution_
    //
    {
      ::std::string& v =
        o.resolution_;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.resolution_value,
        i.resolution_size,
        i.resolution_null);
    }

    // type_
    //
    {
      ::std::string& v =
        o.type_;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.type_value,
        i.type_size,
        i.type_null);
    }

    // path_
    //
    {
      ::std::string& v =
        o.path_;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.path_value,
        i.path_size,
        i.path_null);
    }

    // timeUpload_
    //
    {
      ::time_t& v =
        o.timeUpload_;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i.timeUpload_value,
        i.timeUpload_null);
    }

    // timeModify_
    //
    {
      ::time_t& v =
        o.timeModify_;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i.timeModify_value,
        i.timeModify_null);
    }

    // owner_
    //
    {
      ::std::string& v =
        o.owner_;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.owner_value,
        i.owner_size,
        i.owner_null);
    }
  }

  void access::object_traits_impl< ::Picture, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::Picture, id_sqlite >::persist_statement[] =
  "INSERT INTO \"Picture\" "
  "(\"id\", "
  "\"name\", "
  "\"bytes\", "
  "\"resolution\", "
  "\"type\", "
  "\"path\", "
  "\"timeUpload\", "
  "\"timeModify\", "
  "\"owner\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Picture, id_sqlite >::find_statement[] =
  "SELECT "
  "\"Picture\".\"id\", "
  "\"Picture\".\"name\", "
  "\"Picture\".\"bytes\", "
  "\"Picture\".\"resolution\", "
  "\"Picture\".\"type\", "
  "\"Picture\".\"path\", "
  "\"Picture\".\"timeUpload\", "
  "\"Picture\".\"timeModify\", "
  "\"Picture\".\"owner\" "
  "FROM \"Picture\" "
  "WHERE \"Picture\".\"id\"=?";

  const char access::object_traits_impl< ::Picture, id_sqlite >::update_statement[] =
  "UPDATE \"Picture\" "
  "SET "
  "\"name\"=?, "
  "\"bytes\"=?, "
  "\"resolution\"=?, "
  "\"type\"=?, "
  "\"path\"=?, "
  "\"timeUpload\"=?, "
  "\"timeModify\"=?, "
  "\"owner\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::Picture, id_sqlite >::erase_statement[] =
  "DELETE FROM \"Picture\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::Picture, id_sqlite >::query_statement[] =
  "SELECT "
  "\"Picture\".\"id\", "
  "\"Picture\".\"name\", "
  "\"Picture\".\"bytes\", "
  "\"Picture\".\"resolution\", "
  "\"Picture\".\"type\", "
  "\"Picture\".\"path\", "
  "\"Picture\".\"timeUpload\", "
  "\"Picture\".\"timeModify\", "
  "\"Picture\".\"owner\" "
  "FROM \"Picture\"";

  const char access::object_traits_impl< ::Picture, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"Picture\"";

  const char access::object_traits_impl< ::Picture, id_sqlite >::table_name[] =
  "\"Picture\"";

  void access::object_traits_impl< ::Picture, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Picture, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Picture, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  bool access::object_traits_impl< ::Picture, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Picture, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Picture, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Picture, id_sqlite >::object_type >
  access::object_traits_impl< ::Picture, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Picture, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"Picture\"");
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" INTEGER NOT NULL,\n"
                      "  \"migration\" INTEGER NOT NULL)");
          db.execute ("DELETE FROM \"schema_version\"\n"
                      "  WHERE \"name\" = ''");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"Picture\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"name\" TEXT NOT NULL,\n"
                      "  \"bytes\" INTEGER NOT NULL,\n"
                      "  \"resolution\" TEXT NOT NULL,\n"
                      "  \"type\" TEXT NOT NULL,\n"
                      "  \"path\" TEXT NOT NULL,\n"
                      "  \"timeUpload\" INTEGER NOT NULL,\n"
                      "  \"timeModify\" INTEGER NOT NULL,\n"
                      "  \"owner\" TEXT NOT NULL)");
          return true;
        }
        case 2:
        {
          db.execute ("CREATE TABLE IF NOT EXISTS \"schema_version\" (\n"
                      "  \"name\" TEXT NOT NULL PRIMARY KEY,\n"
                      "  \"version\" INTEGER NOT NULL,\n"
                      "  \"migration\" INTEGER NOT NULL)");
          db.execute ("INSERT OR IGNORE INTO \"schema_version\" (\n"
                      "  \"name\", \"version\", \"migration\")\n"
                      "  VALUES ('', 1, 0)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);

  static const schema_catalog_migrate_entry
  migrate_schema_entry_1_ (
    id_sqlite,
    "",
    1ULL,
    0);
}

#include <odb/post.hxx>
